CREATE TABLE [dbo].[UserAuth] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [UserName]             VARCHAR (8000) NULL,
    [Email]                VARCHAR (8000) NULL,
    [PrimaryEmail]         VARCHAR (8000) NULL,
    [PhoneNumber]          VARCHAR (8000) NULL,
    [FirstName]            VARCHAR (8000) NULL,
    [LastName]             VARCHAR (8000) NULL,
    [DisplayName]          VARCHAR (8000) NULL,
    [Company]              VARCHAR (8000) NULL,
    [BirthDate]            DATETIME       NULL,
    [BirthDateRaw]         VARCHAR (8000) NULL,
    [Address]              VARCHAR (8000) NULL,
    [Address2]             VARCHAR (8000) NULL,
    [City]                 VARCHAR (8000) NULL,
    [State]                VARCHAR (8000) NULL,
    [Country]              VARCHAR (8000) NULL,
    [Culture]              VARCHAR (8000) NULL,
    [FullName]             VARCHAR (8000) NULL,
    [Gender]               VARCHAR (8000) NULL,
    [Language]             VARCHAR (8000) NULL,
    [MailAddress]          VARCHAR (8000) NULL,
    [Nickname]             VARCHAR (8000) NULL,
    [PostalCode]           VARCHAR (8000) NULL,
    [TimeZone]             VARCHAR (8000) NULL,
    [Salt]                 VARCHAR (8000) NULL,
    [PasswordHash]         VARCHAR (8000) NULL,
    [DigestHa1Hash]        VARCHAR (8000) NULL,
    [Roles]                VARCHAR (MAX)  NULL,
    [Permissions]          VARCHAR (MAX)  NULL,
    [CreatedDate]          DATETIME       NOT NULL,
    [ModifiedDate]         DATETIME       NOT NULL,
    [InvalidLoginAttempts] INT            NOT NULL,
    [LastLoginAttempt]     DATETIME       NULL,
    [LockedDate]           DATETIME       NULL,
    [RecoveryToken]        VARCHAR (8000) NULL,
    [RefId]                INT            NULL,
    [RefIdStr]             VARCHAR (8000) NULL,
    [Meta]                 VARCHAR (MAX)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

