/*
Deployment script for FCQ-Brands

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "FCQ-Brands"
:setvar DefaultFilePrefix "FCQ-Brands"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating [dbo].[Brand]...';


GO
CREATE TABLE [dbo].[Brand] (
    [Id]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (50) NOT NULL,
    [Link] NVARCHAR (50) NULL,
    CONSTRAINT [PK_Brand_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Brand|User]...';


GO
CREATE TABLE [dbo].[Brand|User] (
    [Brand] INT NOT NULL,
    [User]  INT NOT NULL,
    CONSTRAINT [PK_Brand|User] PRIMARY KEY CLUSTERED ([Brand] ASC, [User] ASC)
);


GO
PRINT N'Creating [dbo].[UserAuth]...';


GO
CREATE TABLE [dbo].[UserAuth] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [UserName]             VARCHAR (8000) NULL,
    [Email]                VARCHAR (8000) NULL,
    [PrimaryEmail]         VARCHAR (8000) NULL,
    [PhoneNumber]          VARCHAR (8000) NULL,
    [FirstName]            VARCHAR (8000) NULL,
    [LastName]             VARCHAR (8000) NULL,
    [DisplayName]          VARCHAR (8000) NULL,
    [Company]              VARCHAR (8000) NULL,
    [BirthDate]            DATETIME       NULL,
    [BirthDateRaw]         VARCHAR (8000) NULL,
    [Address]              VARCHAR (8000) NULL,
    [Address2]             VARCHAR (8000) NULL,
    [City]                 VARCHAR (8000) NULL,
    [State]                VARCHAR (8000) NULL,
    [Country]              VARCHAR (8000) NULL,
    [Culture]              VARCHAR (8000) NULL,
    [FullName]             VARCHAR (8000) NULL,
    [Gender]               VARCHAR (8000) NULL,
    [Language]             VARCHAR (8000) NULL,
    [MailAddress]          VARCHAR (8000) NULL,
    [Nickname]             VARCHAR (8000) NULL,
    [PostalCode]           VARCHAR (8000) NULL,
    [TimeZone]             VARCHAR (8000) NULL,
    [Salt]                 VARCHAR (8000) NULL,
    [PasswordHash]         VARCHAR (8000) NULL,
    [DigestHa1Hash]        VARCHAR (8000) NULL,
    [Roles]                VARCHAR (MAX)  NULL,
    [Permissions]          VARCHAR (MAX)  NULL,
    [CreatedDate]          DATETIME       NOT NULL,
    [ModifiedDate]         DATETIME       NOT NULL,
    [InvalidLoginAttempts] INT            NOT NULL,
    [LastLoginAttempt]     DATETIME       NULL,
    [LockedDate]           DATETIME       NULL,
    [RecoveryToken]        VARCHAR (8000) NULL,
    [RefId]                INT            NULL,
    [RefIdStr]             VARCHAR (8000) NULL,
    [Meta]                 VARCHAR (MAX)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UserName]...';


GO
CREATE TABLE [dbo].[UserName] (
    [Id]       INT           IDENTITY (1, 1) NOT NULL,
    [AuthId]   INT           NOT NULL,
    [UserName] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_UserName] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[UserName].[IX_UserName]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_UserName]
    ON [dbo].[UserName]([UserName] ASC);


GO
PRINT N'Creating [dbo].[FK_Brand|User_Brand]...';


GO
ALTER TABLE [dbo].[Brand|User] WITH NOCHECK
    ADD CONSTRAINT [FK_Brand|User_Brand] FOREIGN KEY ([Brand]) REFERENCES [dbo].[Brand] ([Id]);


GO
PRINT N'Creating [dbo].[FK_Brand|User_User]...';


GO
ALTER TABLE [dbo].[Brand|User] WITH NOCHECK
    ADD CONSTRAINT [FK_Brand|User_User] FOREIGN KEY ([User]) REFERENCES [dbo].[UserName] ([Id]);


GO
PRINT N'Creating [dbo].[FK_UserName_UserAuth]...';


GO
ALTER TABLE [dbo].[UserName] WITH NOCHECK
    ADD CONSTRAINT [FK_UserName_UserAuth] FOREIGN KEY ([AuthId]) REFERENCES [dbo].[UserAuth] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Brand|User] WITH CHECK CHECK CONSTRAINT [FK_Brand|User_Brand];

ALTER TABLE [dbo].[Brand|User] WITH CHECK CHECK CONSTRAINT [FK_Brand|User_User];

ALTER TABLE [dbo].[UserName] WITH CHECK CHECK CONSTRAINT [FK_UserName_UserAuth];


GO
PRINT N'Update complete.';


GO
